[package]
name = "librespot-protocol"
version = "0.1.1"
authors = ["Paul Liétar <paul@lietar.net>"]
build = "build.rs"
description="The protobuf logic for communicating with Spotify servers"
license="MIT"
edition = "2018"

[dependencies]
protobuf = "~2.8.1"

[build-dependencies]
protobuf-codegen-pure = "~2.8.1"
protobuf-codegen = "~2.8.1"
