[package]
name = "librespot-audio"
version = "0.1.6"
authors = ["Paul Lietar <paul@lietar.net>"]
description="The audio fetching and processing logic for librespot"
license="MIT"
edition = "2018"

[dependencies.librespot-core]
path = "../core"
version = "0.1.6"

[dependencies]
aes-ctr = "0.6"
bit-set = "0.5"
byteorder = "1.3"
bytes = "0.4"
futures = "0.1"
lewton = "0.10"
ogg = "0.8"
log = "0.4"
num-bigint = "0.3"
num-traits = "0.2"
tempfile = "3.1"

librespot-tremor = { version = "0.2.0", optional = true }
vorbis = { version ="0.0.14", optional = true }

[features]
with-tremor = ["librespot-tremor"]
with-vorbis = ["vorbis"]
